export const jobs = [
    {
        id: 1,
        title: "React.Js Application Developer",
        company_name: "Accenture",
        company_logo: "accenture.png",
        min_experience: 2,
        max_experience: 4,
        salary: "Not disclosed",
        location: ["Remote"],
        description: "Design, build and configure applications to meet business process and application requirements. Must have skills :React.js",
        tags: ["react.js", "javascript", "redux", "GIT", "html", "css", "json", "webpack"],
        posted_days_ago: "5+ Days Ago",
        num_reviews: 24099,
        review_star: 4.2,
        apply_url: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4231282-S1650199_en&SRC=RECNau"
    },
    {
        id: 2,
        title: "MEAN/MERN Stack Developer",
        company_name: "Railsfactory",
        // company_logo: "crowdstrike.webp",
        min_experience: 2,
        max_experience: 5,
        salary: "Not disclosed",
        location: ["Remote,", "Mumbai", "Delhi", "Hyderabad", "Pune", "Chennai", "Bangalore/Bengaluru"],
        description: "A BS / MS in Computer Science, Software Engineering, or related field or comparable exp...",
        tags: ["Computer science", "Web application development", "Front end", "backend", "Web technologies", "Front end design",],
        posted_days_ago: "1 Days Ago",
        num_reviews: 1185,
        review_star: 4,
        apply_url: "https://railsfactory.com/careers"
    },
    {
        id: 3,
        title: "Frontend Developer",
        company_name: "In Time Tec",
        company_logo: "dream11.webp",
        min_experience: 2,
        max_experience: 7,
        salary: "Not disclosed",
        location: ["Jaipur", "Bengaluru"],
        description: "The position requires an experienced and ambitious candidate who is passionate about technology and is self-driven. We have an energetic workplace environment where we welcome innovative ideas and offers growth opportunities and positive environment for accomplishing goals. Our purpose is to create abundance for everyone we touch. ",
        tags: ["react.js", "javascript", "redux", "GIT", "html", "css", "json", "webpack", "ui development, api, ajax, material ui, firebase,"],
        posted_days_ago: "3 Days Ago",
        num_reviews: 399,
        review_star: 4.4,
        apply_url: "https://careers.intimetec.in/#!/job-view/react-js-developer-jaipur-rajasthan-india-bangalore-karnataka-india-react-react-js-202402121109005?source=naukri"
    },
    {
        id: 4,
        title: "Node.js-Application Developer",
        company_name: "Accenture",
        company_logo: "accenture.png",
        min_experience: 5,
        max_experience: 4,
        salary: "Not disclosed",
        location: ["Bengaluru",],
        description: "Design, build and configure applications to meet business process and application requirements. Must have skills :Node.js",
        tags: ["javascript", "node", "http", "web services", "css", "git", "json", "html", "rest", "jest", "node.js", "agile"],
        posted_days_ago: "2 Days Ago",
        num_reviews: 46557,
        review_star: 4.2,
        apply_url: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4104841-S1601967_en&SRC=RECNau"
    },
    {
        id: 5,
        title: "Senior Frontend Developer",
        company_name: "tracxn",
        company_logo: "tracxn.png",
        min_experience: 1,
        max_experience: 7,
        salary: "Not disclosed",
        location: ["Bangalore"],
        description: "Experience with web application development Build interactive, responsive & performant front-end interfaces. & Collaborate with Product and UX teams to drive the design decisions. ....",
        tags: ["react.js", "nexy.js", "remix", "vue", "sass", "html", "css", "js"],
        posted_days_ago: "2 Days Ago",
        num_reviews: 2650,
        review_star: 4.6,
        apply_url: "https://careers.tracxn.com/jobs/Careers/660195000003020037/Senior-Frontend-Developer?source=CareerSite"
    },
    {
        id: 6,
        title: "Senior Backend Developer",
        company_name: "tracxn",
        company_logo: "tracxn.png",
        min_experience: 1,
        max_experience: 7,
        salary: "Not disclosed",
        location: ["Bangalore"],
        description: "Experience with backend development Desired Skills (Good if you have): ElasticSearch, MongoDB, MySQL, Redis, Springboot, Crawling/ Web Scrapping, Programming languages(C, C++, Java,Python)",
        tags: ["react.js", "nexy.js", "remix", "vue", "sass", "html", "css", "js"],
        posted_days_ago: "2 Days Ago",
        num_reviews: 2650,
        review_star: 4.6,
        apply_url: "https://careers.tracxn.com/jobs/Careers/660195000003020037/Senior-Frontend-Developer?source=CareerSite"
    },
    {
        title: "React.Js eveloper",
        company_name: "tcs",
        company_logo: "tcs.png",
        min_experience: "6 months",
        max_experience: 2,
        salary: "6 LPA",
        location: ["Ahmedabad,"],
        description: ". We are looking for someone who is well-versed in modern web development workflows and concepts in ReactJS (v18). The ideal candidate should be having key qualities that define a typical programmer, such as optimistic approach to problem solving, non-complacency, willingness to learn and improvise, proficient communication skills and a sincere sense of responsibility towards projects.",
        tags: ["html", "css", "js", "react.js ", "redux", "material ui"],
        posted_days_ago: "30+ Days Ago",
        num_reviews: 80,
        review_star: 4.1,
        apply_url: ""
    },
    {
        title: "Software developer cum digital marketing manager",
        company_name: "Nescode Technologies",
        company_logo: "nes.gif",
        min_experience: 3,
        max_experience: 7,
        salary: "Not disclosed",
        location: ["Bengaluru"],
        description: "We are looking for an experienced and passionate software developer and digital marketing manager who can take up challenging roles where you can contribute to development and social media campaigns.",
        tags: ["seo", "sem", "smo", "Application development", "Affiliate Marketing", "SDLC", "SQL"],
        posted_days_ago: "2 Days Ago",
        num_reviews: 801,
        review_star: 4.1,
        apply_url: "https://www.nescode.com/career/software-developer-cum-digital-marketing-manager/"
    },
    {
        title: "Digital Marketing Executive",
        company_name: "Global Women Power",
        // company_logo: "nes.gif",
        min_experience: 1,
        max_experience: 5,
        salary: "Not disclosed",
        locations: ["Kolkata", "Mumbai", "New Delhi", "Hyderabad/Secunderabad", "Pune", "Chennai", "Bangalore/Bengaluru"],
        description: "Global Women Power is looking for Digital Marketing Executive to join our dynamic team and embark on a rewarding career journey .",
        tags: ["seo", "sem", "smo", "Affiliate Marketing", "SQL"],
        posted_days_ago: "10 Days Ago",
        num_reviews: 991,
        review_star: 4.5,
        apply_url: "https://globalwomenpower.com/jobs/?search_keywords=&selected_category=-1&selected_jobtype=-1&selected_location=india"
    },
    {
        title: "Digital Marketing Executive",
        company_name: "Intersoft Kk",
        // company_logo: "nes.gif",
        min_experience: 1,
        max_experience: 3,
        salary: "Not disclosed",
        location: ["Kolkata", "Mumbai", "New Delhi", "Hyderabad", "Pune", "Chennai", "Bengaluru"],
        description: "We are looking for Plan and execute all web, SEO/SEM, lead generation, email, social media, and display advertising campaigns",
        tags: ["seo", "sem", "smo", "Application development", "Affiliate Marketing", "SDLC", "SQL"],
        posted_days_ago: "2 Days Ago",
        num_reviews: 5666,
        review_star: 4.8,
        apply_url: "https://intersoftkk.com/career/2462"
    },

    {
        title: "Digital Marketing Specialist",
        company_name: "Diagnal Technologies",
        company_logo: "diagnal.gif",
        min_experience: 1,
        max_experience: 3,
        salary: "Not disclosed",
        location: ["Kolkata",
            "Mumbai",
            "New Delhi",
            "Hyderabad/Secunderabad",
            "Pune",
            "Chennai",
            "Bangalore/Bengaluru"],
        description: "Develop branding strategy and execute branding projects positioning Diagnal as an employer of choice for tech professionals. Conduct market research including benchmarking",
        tags: ["Project management",
        "Social media",
        "Employee engagement",
        "Tool design",
        "Market research",
        "Digital marketing",
        "Recruitment",
        "Visual Design",],
        posted_days_ago: "8 Days Ago",
        num_reviews: 16,
        review_star: 4.2,
        apply_url: "https://www.diagnal.com/careers/"
    }
]
